all:
  hosts:
    localhost:
      become: true
      ansible_ssh_user: "{{linux_user}}"
      ansible_sudo_pass: "{{sudo_pass}}"
      ansible_host: 127.0.0.1
      ansible_connection: local
      ansible_host_key_checking: false
      ansible_python_interpreter: "{{ansible_playbook_python}}"
